; EndeavorHumanoid ESP32 Controller Config File

[platformio]
packages_dir = ./.pio/packages

[env]
platform = platformio/espressif32 @ 6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    ; adafruit/Adafruit BNO055@^1.6.4
    br3ttb/PID @ ^1.2.1
    adafruit/Adafruit BNO08x @ ^1.2.5


platform_packages = 
    framework-arduinoespressif32@https://github.com/ricardoquesada/esp32-arduino-lib-builder/releases/download/4.1.0/esp32-bluepad32-4.1.0.zip

[env:my_robot]
build_flags = 
    -D CTRL_MAC=\"98:b6:7f:0a:fa:59\"
    -D IMU_CONFIG=1
    -D SERIAL_DEBUG_MODE=false
    -D FALL_PROTECTION_ENABLED=true
    -D ULT_LOCK=false
    ; -D CONFIG_FILE=robotCustomInfo.h | Uncomment if using a copy of robotInfoDefault.h
